apiVersion: v1
kind: Service
metadata:
  name: sms-service
  namespace: openshop
  labels:
    app: sms-service
spec:
  selector:
    app: sms-service
  ports:
    - protocol: TCP
      port: 8010
      targetPort: 8010
  type: ClusterIP
