apiVersion: v1
kind: ConfigMap
metadata:
  name: openshop-config
  namespace: openshop
data:
  RABBITMQ_URL: "amqp://openshop:openshop123@rabbitmq:5672/"
  ELASTICSEARCH_URL: "http://elasticsearch:9200"
  LOG_LEVEL: "INFO"
  PYTHONPATH: "/app"
