apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshop

resources:
  - ../../base/namespace.yaml
  - ../../base/configmap.yaml
  - ../../services/order-service/deployment.yaml
  - ../../services/order-service/service.yaml

patches:
  - target:
      kind: Deployment
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1

commonLabels:
  environment: dev
