"""Aliyun Phone Number Service (号码认证服务) provider adapter.

Uses alibabacloud_dypnsapi20170525 SDK to send and verify SMS verification codes.
Docs: https://help.aliyun.com/document_detail/85198.html

This provider is dedicated to verification-code scenarios and uses
the Aliyun Number Authentication Service (PNS), which differs from
the regular Dysms SMS API used by AliyunSmsProvider.
"""

import json

import structlog
from alibabacloud_dypnsapi20170525 import models as dypns_models
from alibabacloud_dypnsapi20170525.client import Client as DypnsClient
from alibabacloud_tea_openapi.models import Config as OpenApiConfig

from app.core.config import settings
from app.providers import BaseSmsProvider, SendResult, StatusResult

log = structlog.get_logger(__name__)

_DEFAULT_ENDPOINT = "dypnsapi.aliyuncs.com"


def _build_client(
    access_key_id: str,
    access_key_secret: str,
    endpoint: str,
) -> DypnsClient:
    """Build the Dypns SDK client with the provided AK/SK credentials."""
    api_config = OpenApiConfig(
        access_key_id=access_key_id,
        access_key_secret=access_key_secret,
        endpoint=endpoint,
    )
    return DypnsClient(api_config)


class AliyunPhoneSvcProvider(BaseSmsProvider):
    """Aliyun 号码认证服务 SMS provider.

    Sends SMS verification codes via SendSmsVerificationCode and
    supports code verification via CheckSmsVerificationCode.
    """

    def __init__(
        self,
        access_key_id: str = "",
        access_key_secret: str = "",
        sign_name: str = "",
        endpoint: str = "",
    ) -> None:
        self._key_id = access_key_id
        self._key_secret = access_key_secret
        self._sign_name = sign_name
        self._endpoint = endpoint or _DEFAULT_ENDPOINT

    # ------------------------------------------------------------------
    # BaseSmsProvider interface
    # ------------------------------------------------------------------

    async def send(self, phone: str, template_id: str, params: dict) -> SendResult:
        """Send an SMS verification code using Aliyun SendSmsVerifyCode API.

        Expects params to contain 'code' (the OTP) and 'min' (validity in minutes)
        generated by the caller and already cached in Redis.
        """
        try:
            client = _build_client(self._key_id, self._key_secret, self._endpoint)
            request = dypns_models.SendSmsVerifyCodeRequest(
                phone_number=phone,
                sign_name=self._sign_name,
                template_code=template_id,
                template_param=json.dumps(params, ensure_ascii=False) if params else "",
                return_verify_code=False,
                valid_time=settings.SMS_CODE_TTL,
            )
            response = client.send_sms_verify_code(request)
            body = response.body

            if body.code == "OK" and body.model:
                log.info(
                    "aliyun_phone_svc.send.success",
                    request_id=body.model.request_id,
                )
                return SendResult(
                    success=True,
                    provider_message_id=body.model.biz_id or "",
                )

            log.warning(
                "aliyun_phone_svc.send.failed",
                code=body.code,
                message=body.message,
            )
            return SendResult(
                success=False,
                error_code=body.code or "UNKNOWN",
                error_message=f"{body.code}: {body.message}",
            )

        except Exception as exc:
            log.error("aliyun_phone_svc.send.error", error=str(exc))
            return SendResult(success=False, error_code="SDK_ERROR", error_message=str(exc))

    async def query_status(self, provider_message_id: str) -> StatusResult:
        """The PNS API does not expose a status-query endpoint; return SENT."""
        return StatusResult(provider_message_id=provider_message_id, status="SENT")

